apiVersion: v1
data:
  appInitContainerRepo: "{{ .Values.global.dockerBase }}/{{ .Values.image.repo }}"
  appInitContainerTag: {{ .Values.image.tag }}
kind: ConfigMap
metadata:
  name: zk-app-init-container
  namespace: zk-client