apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-charts.fullname" . }}
  labels:
  {{- include "helm-charts.labels" . | nindent 4 }}
  namespace: zk-client
data:
  appInitContainerRepo: "{{ .Values.global.dockerBase}}/{{ .Values.image.repo}}"
  appInitContainerTag: "{{ .Values.image.tag}}"